@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.sarinsa.magical_relics.common.worldgen.processor;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;