@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.sarinsa.magical_relics.common.ability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;