@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.sarinsa.magical_relics.client.particle;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;