@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.sarinsa.magical_relics.client.screen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;