@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.sarinsa.magical_relics.common.mob_effects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;