@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.sarinsa.magical_relics.client.renderer.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;